title: SEGLH Guidance
description: South East Genomics Laboratory Hub software development guidance.
remote_theme: just-the-docs/just-the-docs
layout: default
baseurl: ""
url: ""

permalink: pretty

# Enable or disable the site search
# Supports true (default) or false
search_enabled: true
search:
  # Split pages into sections that can be searched individually
  # Supports 1 - 6, default: 2
  heading_level: 2
  # Maximum amount of previews per search result
  # Default: 3
  previews: 2
  # Maximum amount of words to display before a matched word in the preview
  # Default: 5
  preview_words_before: 3
  # Maximum amount of words to display after a matched word in the preview
  # Default: 10
  preview_words_after: 3
  # Set the search token separator
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  tokenizer_separator: /[\s/]+/
  # Display the relative url in search results
  # Supports true (default) or false
  rel_url: true
  # Enable or disable the search button that appears in the bottom right corner of every page
  # Supports true or false (default)
  button: false

# For copy button on code
enable_copy_code_button: true

plugins:
  - jekyll
  - jekyll-remote-theme
  - github-pages
  - jekyll-just-the-docs
  - jekyll-last-modified-at

defaults:
  -
    scope:
      path: "docs" # an empty string here means all files in the project
    values:
      layout: default
#      pdf: true


# Aux links for the upper right navigation
aux_links:
  "SEGLH Guidance on GitHub": "https://github.com/moka-guys/guidance"
  "PDF Handbook Download": "guidance_book.pdf"
  "HTML Handbook Download": "guidance_book.html"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Sort order for navigation links
nav_sort: case_sensitive # Capital letters sorted before lowercase

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/moka-guys/guidance"
gh_edit_branch: "master"
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

show_downloads: true

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%Y-%m-%d %H:%M"

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

#exclude: [docs/math/katex/issues.md]

pdf:
   pdf_engine: pdflatex
   template: jekyll-latex-pdf