title: SEGLH Guidance
description: South East Genomics Laboratory Hub software development guidance.
theme: just-the-docs

url: https://moka-guys.github.io/guidance/

aux_links:
  Template Repository: https://moka-guys.github.io/guidance/
